Let the SourceWMTS component accept a tile grid as prop instead of calculating one
MelihAltintas/vue3-openlayers pull request #148
Opened 2023-03-13 13:06 UTC by arildm

## Description

Instead of calculating a tile grid from the projection extent and the tile zoom level, the SourceWMTS now accepts a tile grid directly as a prop.

## Motivation and Context

Fixes #134. It should be possible to pass a tile grid directly. In my case it was essential, because I have a tile grid but my projection doesn't have an extent.

## How Has This Been Tested?

I have done the same change in a local copy of the SourceWMTS component, placed it directly in my JS project and it works well there. (I'd like to test using this branch as the npm dependency, but I'm not sure how to do it.)

## Screenshots (if appropriate):

## Types of Changes

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2023-03-28 18:33 UTC, d-koppenhagen reviewed
I like the option to pass in a TileGrid as a prop.
However, the current implementation will cause a breaking change as there is no no Grid computed when not passed as a property.

I think it would be better to prevent a breaking change here and use the current solution when not TileGrid is passed as a prop.

The changes should also be documented in the recently integrated documentation in this repo.

2023-06-13 06:56 UTC, d-koppenhagen commented
@arildm Do you want to Rebase your changes / apply them on the new TypeScript-based codebase and implement my suggestions?

2023-06-21 14:53 UTC, arildm commented
I have rebased and I'm happy to receive a review!

I haven't actually tested it in an app. (Not sure how I can do that, e.g. what to specify in my `package.json`?)

2023-06-21 18:53 UTC, d-koppenhagen commented
There are several ways actually:

1. Run `npm pack` and copy the `tgz` file into your repos root directory. Change the version number in your `package.json` file to the file name of the copied archive. Run `npm i` to install it from the packed archive
2. Use `npm link`: run `npm run build` in the `vue3-openlayers` project. After building the dist artifacts, make them symlinkable running `npm link`. Open the console in your project and run `npm link vue3-openlayers` to set a symlink from the `vue3-openlayers` dir in the `node_modules` to your local repo (fork).

Another way to test it and to improve the project is: add a demo and enhance the docs.

2023-06-21 20:26 UTC, d-koppenhagen requested changes
Hey, I wonders why not using the specific WMTSTileGrid?

2023-06-21 20:26 UTC, d-koppenhagen commented on docs/componentsguide/sources/wmts/index.md
> +- **Type**: `ol/tilegrid/TileGrid`
```suggestion
- **Type**: `WMTSTileGrid`, see [`ol/tilegrid/WMTS`](https://openlayers.org/en/latest/apidoc/module-ol_tilegrid_WMTS-WMTSTileGrid.html)
```

2023-06-21 20:26 UTC, d-koppenhagen commented on src/components/sources/OlSourceWMTS.vue
> +import TileGrid from "ol/tilegrid/TileGrid";
```suggestion
```

Why no using the specific TileGrid for WMTS as described in the source vector docs: https://openlayers.org/en/latest/apidoc/module-ol_source_WMTS-WMTS.html

2023-06-21 20:26 UTC, d-koppenhagen commented on src/components/sources/OlSourceWMTS.vue
> +    tileGrid?: TileGrid;
```suggestion
    tileGrid?: WMTSTileGrid;
```

2023-06-26 19:50 UTC, d-koppenhagen commented
@arildm okay, I took it over and released the feature with [v1.0.0-next.3](https://github.com/MelihAltintas/vue3-openlayers/commit/e2fa98c3d6ecb998fae02c07f95482e20786899f)

2023-06-26 19:50 UTC, closed without merging